// NOTE: Shared JSON-LD builders for generate-schema-markup.mjs — entity-linked graphs for Google Search and AI Overviews.

export const SITE = 'https://formaa.no';
export const ORG_ID = `${SITE}/#organization`;
export const WEBSITE_ID = `${SITE}/#website`;
export const PROFESSIONAL_SERVICE_ID = `${SITE}/#professional-service`;

export const REGION_LABELS = {
  norge: 'Norge',
  oslo: 'Oslo',
  akershus: 'Akershus',
  buskerud: 'Buskerud',
  ostfold: 'Østfold',
};

export const SERVICE_SLUG_LABELS = {
  '3d-modelering': '3D-modelering',
  branding: 'Branding',
  brukerundersokelse: 'Brukerundersøkelse',
  'cad-modelering': 'CAD-modelering',
  design: 'Design',
  emballasjedesign: 'Emballasjedesign',
  industridesign: 'Industridesign',
  konseptutvikling: 'Konseptutvikling',
  markedsundersokelse: 'Markedsundersøkelse',
  produktdesign: 'Produktdesign',
  prototyping: 'Prototyping',
  redesign: 'Redesign',
  'teknisk-tegning': 'Teknisk tegning',
  validering: 'Validering',
  visualisering: 'Visualisering',
};

const DEFAULT_IMAGE = `${SITE}/assets/images/prosess/3d-modelering.webp`;
const DEFAULT_LOGO = `${SITE}/assets/formaa-logo.svg`;

export function stripHtml(value) {
  return String(value)
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function normalizeCanonical(href) {
  if (!href) return null;
  if (href.startsWith('http://') || href.startsWith('https://'))
    return href.replace(/\/$/, '') || SITE;
  const path = href.startsWith('/') ? href : `/${href}`;
  return `${SITE}${path}`.replace(/\/$/, '') || SITE;
}

export function organizationRef(extra = {}) {
  return {
    '@type': 'Organization',
    '@id': ORG_ID,
    name: 'Formaa',
    url: `${SITE}/`,
    logo: { '@type': 'ImageObject', url: DEFAULT_LOGO },
    ...extra,
  };
}

export function publisherRef() {
  return organizationRef();
}

export function websiteRef() {
  return {
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    name: 'Formaa',
    url: `${SITE}/`,
    publisher: { '@id': ORG_ID },
    inLanguage: ['nb-NO', 'en'],
  };
}

export function breadcrumbList(items, pageUrl) {
  return {
    '@type': 'BreadcrumbList',
    '@id': `${pageUrl}#breadcrumb`,
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function webPage({ url, name, description, inLanguage = 'nb-NO' }) {
  return {
    '@type': 'WebPage',
    '@id': url,
    name,
    url,
    description,
    inLanguage,
    isPartOf: { '@id': WEBSITE_ID },
    publisher: publisherRef(),
  };
}

export function wrapGraph(nodes) {
  return {
    '@context': 'https://schema.org',
    '@graph': nodes,
  };
}

export function serializeGraph(nodes) {
  return `${JSON.stringify(wrapGraph(nodes), null, 2)}\n`;
}

export function scriptBlock(nodes) {
  return `    <!-- NOTE: JSON-LD @graph for Google Search and AI Overviews — generated by scripts/generate-schema-markup.mjs; re-run after SEO/meta changes. -->
    <script type="application/ld+json">
${serializeGraph(nodes)
  .split('\n')
  .map((line) => `      ${line}`)
  .join('\n')}
    </script>`;
}

export function extractHowToSteps(blocks) {
  if (!Array.isArray(blocks)) return [];
  const steps = [];
  for (let i = 0; i < blocks.length; i += 1) {
    const block = blocks[i];
    if (block.type !== 'h2') continue;
    const name = stripHtml(block.text);
    if (!name) continue;
    let text = '';
    for (let j = i + 1; j < blocks.length; j += 1) {
      const next = blocks[j];
      if (next.type === 'h2') break;
      if (next.type === 'p' && next.text) {
        text = stripHtml(next.text);
        break;
      }
    }
    steps.push({
      '@type': 'HowToStep',
      position: steps.length + 1,
      name,
      text: text || name,
    });
  }
  return steps;
}

export function buildCategoryGraph({ url, title, description, serviceSlug, regionSlug, h1 }) {
  const serviceLabel = SERVICE_SLUG_LABELS[serviceSlug] || serviceSlug;
  const regionLabel = REGION_LABELS[regionSlug] || regionSlug;
  const serviceName = h1 || `${serviceLabel} i ${regionLabel}`;
  const countryUrl = `${SITE}/category/${serviceSlug}/norge`;
  const crumbs =
    regionSlug === 'norge'
      ? [
          { name: 'Formaa', url: `${SITE}/` },
          { name: serviceName, url },
        ]
      : [
          { name: 'Formaa', url: `${SITE}/` },
          { name: serviceLabel, url: countryUrl },
          { name: regionLabel, url },
        ];

  return wrapGraph([
    websiteRef(),
    breadcrumbList(crumbs, url),
    webPage({ url, name: title, description }),
    {
      '@type': 'Service',
      '@id': `${url}#service`,
      name: serviceName,
      serviceType: serviceLabel,
      description,
      url,
      inLanguage: 'nb-NO',
      provider: publisherRef(),
      areaServed: { '@type': 'Country', name: 'Norge' },
      image: DEFAULT_IMAGE,
    },
  ]);
}

export function buildArticleGraph({
  url,
  headline,
  description,
  image,
  keywords = [],
  blocks = [],
  breadcrumbTitle,
  datePublished,
  dateModified,
}) {
  const graph = [
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: 'Blogg', url: `${SITE}/blogg` },
        { name: breadcrumbTitle || headline, url },
      ],
      url
    ),
    {
      '@type': 'BlogPosting',
      '@id': `${url}#blogposting`,
      headline,
      description,
      inLanguage: 'nb-NO',
      datePublished: datePublished || '2026-01-01T00:00:00+01:00',
      dateModified: dateModified || datePublished || '2026-01-01T00:00:00+01:00',
      articleSection: 'Blogg',
      keywords,
      author: publisherRef(),
      publisher: publisherRef(),
      mainEntityOfPage: { '@type': 'WebPage', '@id': url },
      image: [image || DEFAULT_IMAGE],
      isPartOf: {
        '@type': 'Blog',
        name: 'Formaa Blogg',
        url: `${SITE}/blogg`,
      },
    },
  ];

  const steps = extractHowToSteps(blocks);
  if (steps.length >= 2) {
    graph.push({
      '@type': 'HowTo',
      '@id': `${url}#howto`,
      name: headline,
      description,
      inLanguage: 'nb-NO',
      step: steps,
    });
  }

  return wrapGraph(graph);
}

export function buildBloggHubGraph({ url, title, description }) {
  return wrapGraph([
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: 'Blogg', url },
      ],
      url
    ),
    webPage({ url, name: title, description }),
    {
      '@type': 'Blog',
      '@id': `${url}#blog`,
      name: 'Formaa Blogg',
      description,
      url,
      inLanguage: 'nb-NO',
      publisher: publisherRef(),
    },
  ]);
}

export function buildDefaultWebGraph({
  url,
  title,
  description,
  breadcrumbs,
  inLanguage = 'nb-NO',
}) {
  const crumbs = breadcrumbs || [
    { name: 'Formaa', url: `${SITE}/` },
    { name: title.split('|')[0].trim(), url },
  ];
  return wrapGraph([
    websiteRef(),
    breadcrumbList(crumbs, url),
    webPage({ url, name: title, description, inLanguage }),
  ]);
}

export function buildProjectGraph({ url, title, description, image }) {
  return wrapGraph([
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: 'Prosjekter', url: `${SITE}/prosjekter` },
        { name: title, url },
      ],
      url
    ),
    {
      '@type': 'CreativeWork',
      '@id': `${url}#project`,
      name: title,
      description,
      url,
      inLanguage: 'nb-NO',
      image: image || DEFAULT_IMAGE,
      creator: publisherRef(),
      publisher: publisherRef(),
    },
  ]);
}

export function buildProjectsHubGraph({ url, title, description }) {
  return wrapGraph([
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: 'Prosjekter', url },
      ],
      url
    ),
    webPage({ url, name: title, description }),
    {
      '@type': 'CollectionPage',
      '@id': `${url}#collection`,
      name: title,
      description,
      url,
      inLanguage: 'nb-NO',
      isPartOf: { '@id': WEBSITE_ID },
    },
  ]);
}

// NOTE: Event hub /arrangement — skisse- og idéworkshop with Event schema for Google.
export function buildArrangementGraph({ url, title, description }) {
  return wrapGraph([
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: 'Arrangement', url },
      ],
      url
    ),
    webPage({ url, name: title, description }),
    {
      '@type': 'Event',
      '@id': `${url}#event`,
      name: 'Skisse- og idéworkshop',
      description:
        'Gratis workshop for deg med en produktidé — tegne og tenke sammen, bli kjent og få et første steg videre.',
      startDate: '2026-08-19T17:00:00+02:00',
      eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
      eventStatus: 'https://schema.org/EventScheduled',
      location: {
        '@type': 'Place',
        name: 'Oslo-området',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Oslo',
          addressCountry: 'NO',
        },
      },
      organizer: { '@id': ORG_ID },
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'NOK',
        url,
        availability: 'https://schema.org/LimitedAvailability',
      },
    },
  ]);
}

export function buildEnLandingGraph({
  url,
  title,
  description,
  serviceName,
  serviceType,
  breadcrumbName,
}) {
  return wrapGraph([
    websiteRef(),
    breadcrumbList(
      [
        { name: 'Formaa', url: `${SITE}/` },
        { name: breadcrumbName, url },
      ],
      url
    ),
    webPage({ url, name: title, description, inLanguage: 'en' }),
    {
      '@type': 'Service',
      '@id': `${url}#service`,
      name: serviceName,
      serviceType,
      description,
      url,
      inLanguage: 'en',
      provider: publisherRef(),
      areaServed: 'Worldwide',
    },
  ]);
}
